### ISSUE TITLE
FxA profile view (settings)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#11]
When use Lockbox to manage my passwords, I want to know my login credentials are secure and only accessible to me. And I want to have full control over that account including  _seeing_ the ability to unlink it.

## Acceptance criteria
* Should see FxA avatar & email & display name (if set) to see the account linked

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979892_Account

**Zeplin**
https://zpl.io/beYM3Wz

Requires #22

**Comment by sashei** [comment]
@changecourse @nickbrandt is there a placeholder image for before the profile image has loaded / if the user doesn't have one?

**Comment by nickbrandt** [comment]
@sashei yep, we'll be using the same as what FxA uses as the default. I uploaded another screen with this asset available for export: https://zpl.io/VD49AmW

I also noticed its a bit hard in zeplin to select the oval with the shadow on it for the avatar, so including those specs below for you as well (should be Material Design's 1dp elevation).

<img width="284" alt="screen shot 2018-11-06 at 9 25 08 am" src="https://user-images.githubusercontent.com/5185090/48078168-1a7cb000-e1a6-11e8-8974-150034699f09.png">

**Comment by sashei** [comment]
@nickbrandt awesome, thanks for the quick turnaround on those assets !!
