### ISSUE TITLE
Record settings telemetry events

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-android#120]
Depends on #37 
Depends on #6 

Record telemetry events for:

* ~The Settings view is displayed~ (done via #259)
* ~The FAQ is opened~ (done via #259)
* ~The Provide Feedback is opened~ (done via #259)
* The autolock timer option list is expanded 
* A setting is changed

Blocks #14

**Comment by devinreams** [comment]
@linuxwolf @irrationalagent sorry but I didn't quite follow the resulting back and forth about all route actions being telemetry actions. does #259  mean these setting events are completed? I don't think so but I also don't think this is "in progress" if not...

https://github.com/mozilla-lockbox/lockbox-android/blob/fab63bbc495dd1116d5c995f41aa3b9ee4760151/app/src/main/java/mozilla/lockbox/action/RouteAction.kt#L21-L23

**Comment by irrationalagent** [comment]
yea backlog is right, those events were only for the setting views not the events associated with setting changes, not started on the proper settings events yet.
