### ISSUE TITLE
Record Account telemetry events

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-android#121]
Depends on #22 
Depends on #11 
Depends on #9 

Record telemetry events for:

* [x] The user begins the login process
* [x] The Account view is opened
* [x] ~Click "Get Started"~ -> `RouteAction.Login`
* [ ] Click login before the FxA flow begins -- this telemetry is gathered on the FxA side, not in our app
* [x] ~The app is reset (`settings_reset`) / Disconnect~ -> `object Reset : SettingAction(TelemetryEventMethod.setting_changed, TelemetryEventObject.settings_reset, null)`

Blocks #14

**Comment by irrationalagent** [comment]
So we already record an event when the screen prompting to login is shown https://github.com/mozilla-lockbox/lockbox-android/blob/a911c4e0c97abe45e5455dd9a5b52853d0a37a5b/app/src/main/java/mozilla/lockbox/action/RouteAction.kt#L22

and when a user opens account settings
https://github.com/mozilla-lockbox/lockbox-android/blob/master/app/src/main/java/mozilla/lockbox/action/RouteAction.kt#L24

the only other event that I think would be plausible to add on our end is when the user actually taps the login button immediately before the flow is handed over to FxA.

**Comment by eliserichards** [comment]
It looks like "Get Started" and "reset" are already in the app. I confirmed with @sashei that the 4th item ("Click login before the FxA flow begins") would happen on the FxA side and not directly from our app. Given those things, I think this issue can be closed.
