### ISSUE TITLE
Record autofill telemetry events

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-android#122]
Record telemetry events for:

* Autofill opens while locked
* Autofill is unlocked, or opens while unlocked
* A credential is filled

Requires #214
Blocks #14

**Comment by irrationalagent** [comment]
So, the way the [autofill action](https://github.com/mozilla-lockbox/lockbox-android/blob/76145359c70508beef3fb0eb017011fbedbef00a/app/src/main/java/mozilla/lockbox/action/AutofillAction.kt) is structured today, it looks like we can straightforwardly add three events? 

`TelemetryMethod`: `autofill_single`, `autofill_multiple`, `autofill_cancel`
`TelemetryObject`: `autofill`

Am I correct in interpreting that the `Complete` is the case where only one credential matches, and `CompleteMultiple` where there are many?

Also, we  probably want to write unit tests such that the actual password/login doesn't get into the telemetry event. 

^^ that seems only to cover the third requirement above, however (which is the most important one). In an ideal world we would also have:

`TelemetryMethod`: `autofill_locked`, `autofill_unlocked`

To record an event reflecting the lock state when autofill is opened. However I would call this lower priority than the events that fire when something was actually autofilled, or at least when a credential was provided to the autofill api. In other words, its more important to record the number of times autofill was actually used than record the number of times it was opened.

**Comment by linuxwolf** [comment]
[ cc'ing @sashei / @jhugman / @eliserichards for details/clarifications ... ]

The three telemetry events you note are the most straightforward to add, and your interpretation of what each maps to is (mostly) correct.  "Mostly" in that Android only informs Lockbox when it needs credentials for autofilling, not when the credential is (or is not) actually filled.

I think we'll ultimately need to add at least one additional autofill actions: `Autofill.Search` for when a user taps "Search Firefox Lockbox" to find a better match), and wire it (and the others) up in the `LockboxAutofillService` to more holistically record interactions.

It's important to note that -- right now -- `AutofillAction` is only in use when a user needs to interact more directly with Lockbox during autofill:

* needs to unlock Lockbox to continue
* decides to search for a (better) matching credential

I suspect/suggest we'll need to extend this action/store's use beyond the `AutofillRootActivity` and into the `LockboxAutofillService` to properly record the desired telemetry.

**Comment by irrationalagent** [comment]
> It's important to note that -- right now -- `AutofillAction` is only in use when a user needs to interact more directly with Lockbox during autofill:
> 
>     * needs to unlock Lockbox to continue
> 
>     * decides to search for a (better) matching credential
> 

So if a form is filled through Lockbox without user intervention, then we would not record an event currently?
> 
> I suspect/suggest we'll need to extend this action/store's use beyond the `AutofillRootActivity` and into the `LockboxAutofillService` to properly record the desired telemetry.

**Comment by sashei** [comment]
Ok! I had a few points of clarification:

- We don't have the infrastructure in place in the `Autofill` flow to send any telemetry events now, despite using the `AutofillAction`s there, so some work is required to introduce that.
- There's a subtle difference between `AutofillAction.CompleteMultiple` and `AutofillAction.Complete`:
  - `AutofillAction.CompleteMultiple` is used when we have unlocked the app and are using the app package name (or website) to suggest a list of entries to the autofill service. It's possible that this will be a list of only one entry despite the name. 
  - `AutofillAction.Complete` is used when a user selects a single entry from the search interface.

If we want to add more metrics around whether a credential is actually used or not, it's technically possible via the autofill API but will be a new development feature to implement.
