### ISSUE TITLE
Explore Leak Detection

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-android#140]
Explore options for detecting and reporting memory and/or resource leaks.

Ideally the solution becomes part of CI builds and tests.

Possible options:

* [LeakCanary](https://github.com/square/leakcanary)

**Comment by linuxwolf** [comment]
Something that came up during an IRL review.

@mozilla-lockbox/mobile-engineering drop any suggestions!

**Comment by sashei** [comment]
+1 for LeakCanary, was really useful in a previous app I've worked on, and plays well with Rx.

There is a static analyzer that Facebook makes (leakcanary is made by Square) called [Infer](https://fbinfer.com/docs/getting-started.html) that I have no experience with, but could be useful as a CI tool (IIRC LeakCanary only really works when you're looking at the emulator or device while using the app).

**Comment by devinreams** [comment]
With #142 merged shall we consider this "complete" or leave it open (back in the backlog? inbox?) to remind us to explore/review further?

**Comment by linuxwolf** [comment]
[ cc all of @mozilla-lockbox/mobile-engineering ]

I lean toward leaving it open for a sprint, and see how it works out.

**Comment by sashei** [comment]
^ jinx on the `cc`

I feel that future issues with LeakCanary should be addressed separately from this story. There isn't much definition in the ticket, but I left it open because we may want to include leak detection / monitoring at a CI level. LeakCanary only works on devices / emulators when a user is looking at them.

**Comment by linuxwolf** [comment]
> I feel that future issues with LeakCanary should be addressed separately from this story. There isn't much definition in the ticket, but I left it open because we may want to include leak detection / monitoring at a CI level. LeakCanary only works on devices / emulators when a user is looking at them.

I agree about future issues, but I think it's also worth keeping open for a bit to see if it's actually useful.  I would like CI gatekeepings, assuming they're useful.

**Comment by devinreams** [comment]
In advance of "finishing" this sprint tomorrow, consider this a prompt for any initial thoughts or observations during this sprint (if any).

**Comment by devinreams** [comment]
Follow up at #172 to add to CI
