### ISSUE TITLE
Metrics dashboard

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#16]
Requires #15 
Requires #14

**Comment by sandysage** [comment]
Moving to 'in progress' based on the status update @irrationalagent gave in stand up today.

**Comment by devinreams** [comment]
Dashboard was quickly shared today. Any other updates (extra telemetry events, cut-off at launch) will happen as part of regular review and maintenance. I think this is safe to close as done!

Thanks @irrationalagent
