### ISSUE TITLE
Security review and acceptance

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#17]
- [x] security review from sec eng team
  - 📆 scheduled January 21, 2019
  - (private) https://docs.google.com/document/d/16R-GqBAeXs70p7Hkj-BmRczirkGuJIyknRuIexbtlwY/edit
- [x] security testing from sec PI team
  - 🐛 https://bugzilla.mozilla.org/show_bug.cgi?id=1519765

**Comment by sashei** [comment]
Lockbox-team step: audit possibly "malicious" third-party dependencies as identified by @mcomella :
- `implementation 'jp.wasabeef:picasso-transformations:2.2.1'`
- `implementation 'com.github.magiepooh:recycler-itemdecoration:1.1.1@aar'`
- `implementation 'com.f2prateek.rx.preferences2:rx-preferences:2.0.0'`
