### ISSUE TITLE
Implement the robot pattern for UI testing for the app

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#171]
How to get espresso tests properly and fully going. Knowledge needed from @jhugman

Examples:

- testing fingerprint reader
- device PIN dialog

**Comment by jhugman** [comment]
The team met and discussed: 

 * UI versus headless tests. 
 * Units as vertical slices of the app (i.e. we can do unit tests that _are_ unit tests.
  * UI components as units needed testing.
 * UI test frameworks (low level), and building higher level DSLs to make them more expressive and less brittle. 
   - Navigator patterns: navigator objects that know how to route between screens in the app
   - Robot pattern: build a robot per screen of the app, and then use them to build an expressive DSL.

From this meeting, a number of decisions were taken in this meeting:

 * a set of robots to cover the app. This story will morph into this.
 * a way of testing standalone UI components. Ideally this shouldn't ship with the release APK.
 * that we should continue with our testing of Presenters and Stores, which should avoid having android views in it but test a fragment with a UI test when we start adding more code to it. We should document this in an ADR.

This story will morph into the first two of these points.

Unresolved: 
 
 * some tests need a device
 * some tests need an emulator. e.g. faking fingerprinting
