### ISSUE TITLE
Welcome Screen Styling

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#175]
### Acceptance criteria

Welcome screen matches designs

### Visual Design

**InVision**
Welcome (w/ 'Get Started' button): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/310349653_Welcome

**Zeplin**
Welcome (w/ 'Get Started' button): https://zpl.io/VDzrg4v

**Comment by diegolucasb** [comment]
Hi @sashei. Could you share the images and the colours code for this welcome screen layout?

**Comment by sashei** [comment]
Hi @diegolucasb ! Great question; I don't know exactly what the access permission are for the above links but let's see if @changecourse or @nickbrandt can help you out :)

(caveat: they might not be online until tomorrow morning, north america-time)

**Comment by changecourse** [comment]
Hey @diegolucasb, thanks for your willingness to help out! 

The invision link posted above should be publicly accessible, and I'll go ahead and invite you to our Zeplin project via the gmail address associated with your profile. You'll have to create an account with them, but then you'll have access to all colors, specs, and assets associated with that screen. Please let me know if you have any additional questions, or trouble getting access. 😄

**Comment by diegolucasb** [comment]
Thank you @changecourse. Now I'm able to see Zeplin project

**Comment by diegolucasb** [comment]
@changecourse, in order to get the expected result, I'd like to know if it is possible to change `nessie` PGN (or vector image) transparency. It must be transparent only below the waves.

For you to understand what I'm saying, this is the screenshot I'm working on:
<img width="335" alt="screen shot 2018-11-05 at 22 34 38" src="https://user-images.githubusercontent.com/4621339/48035508-7b2acf00-e14b-11e8-8431-f37899f03b85.png">

These parts marked by a red arrow, should not be seen. So, I believe the best solution is to make this small change at the PNG or SVG `nessie` file.

I tried to change it by myself, but I don't have the right tool, either knowledge for that.

What do you guys think?

**Comment by nickbrandt** [comment]
@diegolucasb Hey Lucas, thanks for your help with this! I believe I now have the asset as you need it, available here: https://zpl.io/VDzrg4v

The background of the PNG now has the gray except below the wave line. Let me know if this works for you or if any mods are needed.

**Comment by sashei** [comment]
😆 this is exactly how we did it on iOS

**Comment by diegolucasb** [comment]
Thank you @nickbrandt! Now I get the expected result! Soon I'll open a PR

**Comment by devinreams** [comment]
Hi @diegolucasb thank you for jumping in to help with the project!

Are you still interested in submitting a PR to layout this welcome screen? We are considering working on it ourselves in the next ~1-2 weeks if not. No pressure either way, thanks again for volunteering. 😄

**Comment by diegolucasb** [comment]
Hi, @devinreams no pressure at all. Helping this project is a pleasure for me! I will submit my PR in this following week (probably on this next Wednesday). I sorry, last week had been busier than usual that's why I couldn't finish this issue!

**Comment by devinreams** [comment]
> will submit my PR in this following week (probably on this next Wednesday).

That's excellent! Thank you, we look forward to anything you're able to help contribute. 🙌 

>last week had been busier than usual that's why I couldn't finish this issue!

Not a problem at all, we just didn't want to step on your toes if you were already working on it. 👌
