### ISSUE TITLE
Google Play Store Alpha Submission

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#18]
Depends on #111 

- [x] upload APK (build 2050) @devinreams 
- [x] upload CSV of testers to Closed (Alpha) track @devinreams 
- [x] email the testers @sandysage 
- [x] go back and upload the testers' _real_ Play Store emails @devinreams

**Comment by devinreams** [comment]
@sandysage I will need your help to wrap this one up:

1. I need CSV of emails we originally emailed and want to be in this "Closed" Alpha release (email must match what we have on file)
2. then we need to collaborate on another email to send everyone to join the testing on the Play store
  - letting them know the email/account they give us needs to match what they use to sign into the store on their device (perhaps they submit a separate form where we can capture that address? lesson learned here..)
3. then we will likely hear from people that don't have their Mozilla (or whatever email they provided us) associated with their device and we'll need to add those people again

The alternative to having to do Step 3 is we open this up as an "Open" Beta release (but then anyone can find it in the store and try it).

**Comment by sandysage** [comment]
@devinreams Our internal Alpha release sign up form allows Mozillian testers to use any email address they prefer (not restricted to @mozilla.com). Right now that list consists of ~100 emails. I think it's limited because so many people signed up for 'early access' on our public Beta list.

As much as I'd like to skip steps here, I don't suggest we open up the Beta until we have autofill and a few other P1s in place.

**Comment by devinreams** [comment]
@sandysage cool, I thought that was the case but wanted to share a bit more context around open/closed and the pros and cons.

Here's what I propose then:

- draft and collaborate on an email to this list of testers explaining they can now open https://play.google.com/apps/testing/mozilla.lockbox and begin downloading/updating the app in the store
- let them know if they get the error that they have not been invited/given access to test, they just need to go back to our Google Form (provide that URL) and give us their Gmail/Google Play address they use to log in to the store

Then I will re-load those additional emails in Play console and we can email them at that time to let them know they have access (for real).

And I suggest we update our internal forms to ask for their "Contact Email" (eg: `firstname@example.com`) and "Google Play Email" (eg: `...@gmail.com`)

**Comment by devinreams** [comment]
OK, everyone has been emailed as of this morning and it looks like some folks are starting to download the Alpha (Build 2050) based on what the Play Console is telling me.

We also saw a few new email (Play Store) addressess submitted. I get a daily report of all new additions and will upload (and email everyone to confirm they’ve been added) as often I get these reports. I will also routinely upload new builds to the store for distribution to these testers.

We are officially Alpha in the Play Store!
