### ISSUE TITLE
Fix crash and provide useful message when  not connected to the internet

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-android#185]
We need to provide messages to the user when content doesn't load due to connectivity issues. Along with providing messaging to the user, we also need to allow for the action of "retrying" once their connection is restored.

- fix the crash
- display dialog to the user

### Visual Design
No Internet - FxA: https://zpl.io/aRE9WQE
No Internet - Webview: https://zpl.io/VD4oqYO
No Internet - Entry List (Unpopulated): https://zpl.io/25woG3e
No Internet - Entry List (Populated): https://zpl.io/aRE9WAv

**Comment by sashei** [comment]
Currently, the FxA library will actually crash the app when this is the case. I'd like to prioritize this issue to avoid those crashes if it's alright with y'all @sandysage @devinreams

**Comment by eliserichards** [comment]
**Open questions**
* When do we want to check the connection?
* What is the function of “retry” button? do we want to kick off sync? check connection status again?
* [Design] What is the expected transition of the notification? Will it drop down/slide in?

**Comment by linuxwolf** [comment]
>     When do we want to check the connection?

I think it is sufficient to check why it failed when we get an exception; e.g., attempt the (fxa/sync/webpage) action, and react to that.  I don't _think_ we have to be more proactive.

>     What is the function of “retry” button? do we want to kick off sync? check connection status again?

I think the general behavior is to try the failed network-dependent action again -- sync for item list/detail, reload the FAQ/feedback for those webpage actions, retry FxA if that

**Comment by nickbrandt** [comment]
@eliserichards I don't have strong feelings about the animation for this, but Sliding Down from under navigation bar would be a nice way to handle this unless it requires a significant amount of effort.

**Comment by devinreams** [comment]
Excellent work on an excellent user feature, thanks @eliserichards and team!
