### ISSUE TITLE
Google Play Store Submission

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#19]
Depends on #111 
Depends on #36

**Comment by devinreams** [comment]
Build 3024 is in Play Store artifacts and released to the internal (closed) test tracks. 🚂

**Comment by devinreams** [comment]
I cherry-picked last-minute analytics fixes/commits to "production" branch:
https://github.com/mozilla-lockbox/lockbox-android/commits/production

Build 3137 is the new artifact for release:
https://app.bitrise.io/build/8b31a340ce620575

It's in the Play Store "internal" and "Alpha" tracks ready for promotion to "Production".

Release Management will promote to Production on Tuesday at 10 AM UTC. 🕙
