### ISSUE TITLE
"Can't connect" message needed if the WebView can't see the internet

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockbox/lockbox-android#190]
When the user tries to log in (get started) without an internet connection, she is presented with a blank screen.

When the user tries to log in (get started) with a slow internet connection, she is presented with blank screen for quite a while before being presented with the loading spinner.

**Comment by nickbrandt** [comment]
@jhugman we have an issue for no internet connection on various screens (#185 ). Does it make sense to close this in favor of that, or would you prefer these be broken out?

**Comment by sandysage** [comment]
Closing as a duplicate of #185
