### ISSUE TITLE
[Crash] App crashes on orientation changed, when fingerprint dialog is displayed

### ISSUE THREAD

**Issue by ioana-farcas** [mozilla-lockbox/lockbox-android#194]
Go to Lock screen or Settings screen. Tap on Unlock button or toggle button for enabling fingerprint. After the fingerprint dialog is displayed, change the orientation of the device => app crashes

**Comment by devinreams** [comment]
@ioana-farcas I'm moving this to In Progress because I think you said you were looking into it? If not feel free to move back to "On Deck".

**Comment by ioana-farcas** [comment]
@devinreams After implementing the fallback, the app is not crashing any more. What happens is that when the orientation is changed while the dialog is displayed the sensor is canceled (an error is received), so the dialog should be dismissed and the user should remain in Locked screen. But because on orientation changed the app tries to recreate everything, the dialog is displayed with the sensor canceled error, and when the error is received the app falls back to pin.
I added a fix so that the app will not recreate the dialog when orientation changes, but now the app crashes because of a lifecycle issue. And the error I see is not that one, I can check if this was the case  before the fallback implementation.
