### ISSUE TITLE
No saved entries (list view)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#21]
When I have no entries saved in my Lockbox app, I need to know how to get credentials on mobile.

## Acceptance criteria
* Should prompt for “turn on Sync in Firefox”
* Should inform how to save credentials in Firefox if none saved

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979875_Entry_List_-_Empty_State

**Zeplin**
https://zpl.io/bAqXRlB

**Comment by eliserichards** [comment]
Looks like this might work already (based on the code). Do we have a test account with zero entries to try out? 

https://github.com/mozilla-lockbox/lockbox-android/blob/55acd9b1076afd184bd7927693f126685c98487c/app/src/main/java/mozilla/lockbox/adapter/ItemListAdapter.kt#L39

**Comment by devinreams** [comment]
Yes! Sorry for not sharing earlier:
dreams+appletester@mozilla.com

...with the same shared password as the others. Please message me separately if you need a copy or search the dev mailing list history for test accounts

**Comment by devinreams** [comment]
I just signed in with a brand new "empty" account `firefoxlockbox+empty@gmail.com` and it shows a blank white entry list...

![img_1586](https://user-images.githubusercontent.com/49511/51286695-4f309300-19b1-11e9-8a23-66a3eb77bfc8.jpeg)


In other words, it's missing the "No Entries Found" heading, body, and link to learn more. This issue should indeed still remain "open" to finish up.
