### ISSUE TITLE
Allow Lockbox to be a Credential Provider for Autofill services

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#214]
**Purpose**: Register for `android.permission.BIND_AUTOFILL_SERVICE` and make sure datastore is accessible in the Lockbox AutofillService.

### User-facing Acceptance Criteria

Lockbox will show up on the device in the list of Credential Providers (may need to enable in Settings).

### Engineering Notes

In addition to adding the permission, make sure you can access the Datastore in the `onConnected` AutofillService lifecycle method. This story is primarily infrastructural.

**Comment by grigoryk** [comment]
Perhaps this could be implemented as an android-component (https://github.com/mozilla-mobile/android-components/issues/1581)? What do you think? It'd be nice to have this in the reference-browser, and perhaps in Fenix, and all of these (+Lockbox) is/will be using a common `service-sync-logins` data layer.

**Comment by sandysage** [comment]
@grigoryk It's something we've considered with the Android Components team. At this point in time, we're first defining it for Lockbox as the initial Firefox Android product to offer this service.

We believe that the right combination of Lockbox and browser (ie reference browser) features can provide our shared users with login autofill AND management that aligns with their expectations. In which case, Lockbox would be the only credential provider needed. And if we're wrong, it doesn't preclude us from leveraging the work done for Lockbox in a way that can be later supported in the reference-browser (ie generalized as a component later).

[The password related features are prioritized as such in the reference browser queue](https://github.com/mozilla-mobile/reference-browser/issues?q=is%3Aopen+is%3Aissue+label%3AFeature%3APasswords). We'll first focus on providing an MVP experience between Lockbox and Fenix for Q2 2019. We'll learn from that rollout as to where and how we can improve, and then decide the future of product lines and what features are a 'must'.

@bbinto @st3fan Did I accurately capture our decisions thus far?
