### ISSUE TITLE
Authenticate via fingerprint or PIN to autofill when the app is locked

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#216]
### Acceptance Criteria

Attempting to autofill with a credential from Lockbox while the app is locked will prompt the `DialogFragment` with either fingerprint or PIN authentication.

#### Documentation

[User Authentication](https://developer.android.com/reference/android/service/autofill/AutofillService#user-authentication)

#### Implementation
This involves adding the [`setAuthentication`](https://developer.android.com/reference/android/service/autofill/FillResponse.Builder#setAuthentication(android.view.autofill.AutofillId[],%20android.content.IntentSender,%20android.widget.RemoteViews)) call to the `FillResponse` object when returning from the `buildFillResponse` method in the `LockboxAutofillService`.

#### Possible Gotchas
In order to get a list of potential credentials, the `DataStore` has to be unlocked, so you will need to capture its lock state before unlocking it, use _that_ state to determine when to add the authentication view in the `buildFillResponse` method, and lock it again if the authentication step fails.

depends on #214

**Comment by jhugman** [comment]
@changecourse @nickbrandt 

What should we do in the cases of: 

 * [ ] autofill text boxes are detected but domain is not detected, 
 * [ ] domain is detected, but domain isn't matched by a credential we have in the data store?
 * [ ] lockbox is locked, i.e. authentication is required, but domain isn't matched by a credential we have in the data store.

This feels like we should shell out to a version of the item list + filter; but once an item is selected, we should go back and fill the view in the native view. 

I don't think there are stories to cover any of these cases.

**Comment by linuxwolf** [comment]
@jhugman 
I think the answer to all of your questions would be addressed with (recently added) #421.  The designs do call for an interface that the user can search for a (better) match, but was not completed when we closed #215.
