### ISSUE TITLE
Get Started page (onboarding)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#23]
## Acceptance criteria
* Should reinforce value prop
* Should understand the requirements to using the app
   * a Firefox Account with saved logins (and Sync enabled?)
* Should have one call to action to 'get started'

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/310349653_Welcome

**Zeplin**
https://zpl.io/VDzrg4v

**Comment by sandysage** [comment]
I think this is a duplicate of #175. Double check and close this if so.

**Comment by nickbrandt** [comment]
Yes, I think #175 was created when the baseline Welcome page (placeholder) was developed, in order to capture the styling fixes. So this is no longer needed.
