### ISSUE TITLE
Revisit Telemetry and get basic core ping sent

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#230]

**Comment by linuxwolf** [comment]
asking the experts, it might be due to not explicitly scheduling any pings ...

**Comment by devinreams** [comment]
Just so I don't lose it and can easily re-find, two potentially useful bits:

- the Slack thread that kicked this off from @linuxwolf: https://mozilla.slack.com/archives/CA4JKKLSG/p1543338691819500

- email thread about testing Telemetry: https://groups.google.com/a/mozilla.com/d/msgid/mobile-all/CABupmeDgMfjz%3Dqi4m%2B23BP2jL5%2ByQV-eruCcPRUMErQLyUZRZw%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by linuxwolf** [comment]
>     * email thread about testing Telemetry: https://groups.google.com/a/mozilla.com/d/msgid/mobile-all/CABupmeDgMfjz%3Dqi4m%2B23BP2jL5%2ByQV-eruCcPRUMErQLyUZRZw%40mail.gmail.com?utm_medium=email&utm_source=footer

We've got the appropriate mock points in place, but we could do better to ensure events that should queue a telemetry event really are.
