### ISSUE TITLE
Quiting out of the Lockbox app (and reopening) forces user to sign back in

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-android#239]
Steps to reproduce:
1. Open app (tested on Master)
2. Authenticate via FxA
3. Get to entries list
4. Quit out of app (and dismiss from background)
5. Reopen App
6. Presented with Welcome Screen, forced to authenticate again

This may already be a known issue/hasn't been addressed yet, but I couldn't find an existing issue to reflect it.

**Comment by linuxwolf** [comment]
This should be addressed via #144
