### ISSUE TITLE
Upgrade Android-Components to 0.35.1

### ISSUE THREAD

**Issue by ncalexan** [mozilla-lockbox/lockbox-android#241]
Update Android Components to version 0.35.1 that provides needed improvements to the `FirefoxAccount` class.

**Breaking Changes**
Access tokens can only be obtained for a single scope, rather than all scopes.
* Lockbox **MUST** only ask for `Constant.FxA.oldSyncScope` when obtaining the access token
* Lockbox **MUST** still ask for all scopes when authorizing via `getOAuthURL` + webView.

## Original Description

After https://github.com/mozilla/application-services/issues/252, Lockbox for Android should be able to unit test the a-s logins Rust code (at least on Linux and macOS/Darwin).

This ticket tracks wiring that up on the Lockbox side.

**Comment by ncalexan** [comment]
This will depend on a-c 0.34.0 (or greater) which will depend on a-s 0.11.1 (or greater).  I'll update with a PR to sketch how this will go.

**Comment by linuxwolf** [comment]
Closed via #337
