### ISSUE TITLE
Use a-s megazord/composite in Lockbox

### ISSUE THREAD

**Issue by ncalexan** [mozilla-lockbox/lockbox-android#242]
This ticket tracks using the a-s-provided megazord/composite builds from https://github.com/mozilla/application-services/issues/263.

**NOTE:** This depends on a-c 0.35.0 or later

**Comment by ncalexan** [comment]
This will depend on a-c 0.34.0 (or greater) which will depend on a-s 0.11.1 (or greater). I'll update with a PR to sketch how this will go.

**Comment by ncalexan** [comment]
Just an update on this:
- the Gradle plugin that helps consume megazords is [published](https://plugins.gradle.org/plugin/org.mozilla.appservices), with [initial documentation](https://mozilla.github.io/application-services/docs/applications/consuming-megazord-libraries.html)
- a-s v0.12.0 is [published](https://github.com/mozilla/application-services/releases/tag/v0.12.0)
- waiting to bump a-c (ticket link to follow)
- then either a Lockbox engineer or I can finish this PR

**Comment by ncalexan** [comment]
Hmm, this was incorrectly closed in #337, I think; but let's avoid confusion with a new ticket.

**Comment by devinreams** [comment]
Whoops, waffle's fault I think, not mine. Closing again.
