### ISSUE TITLE
Sync is not working on initial sign in

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockbox/lockbox-android#244]
## Steps to reproduce

1. Open Lockbox on any device
2. Tap on "Get Started"
3. Login with a valid username and password.
4. Wait for sync

### Expected behaviour
Sync is performed and a list of logins should populate the "All entries" screen

### Actual behaviour
No sync is performed

### Device and build information
- Nexus 5 (Android 6.0.1)
- HTC Desire 820 (Android 6.0.1)
- Nokia 6 (Android 7.1.1)
- OnePlus 5T (Android 8.1.0)
- Google Pixel (Android 9)
- [Build #1316](https://app.bitrise.io/build/67245d12e783e79d)

### Notes

- Nothing was synced even after 20 minutes of waiting
- [Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2624537/log.txt)
- ![screen](https://user-images.githubusercontent.com/17178945/49152911-da2fce00-f31c-11e8-8205-e018547d7fd0.png)

**Comment by devinreams** [comment]
@sashei has some ideas about this...

**Comment by bsurd** [comment]
Reopening this issue as sync still does not seem to work reliably.

Scenario:
- For each step I've tried with a fresh instance of the app (cleared data/fresh install)
:x: Login on old accout > data is not synced
:heavy_check_mark: Login on freshly created account > save some logins on desktop or mobile > sync > login on lockbox, login on old account worked as well after logging out this time
:x: Login on newly created account > data is not synced
:x: Login on old accout > data is not synced
- After sync worked in the second step, it continued working until I cleared the app data

**Comment by devinreams** [comment]
With the latest autolock code landed at #240, I believe I consistently see the "Syncing.." toast appear on unlock, as expected.

But I do not see it run during the very first sign in. I am greeted with an empty/blank list view. I have to hard quit the app and re-open for it to sync.

@mozilla-lockbox/mobile-engineering does that match what you've been seeing in recent testing yourselves?
