### ISSUE TITLE
Confirm FxA Screen (onboarding)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#25]
## Acceptance criteria
* When signing in to FxA and email authentication is required, should display an affordance to user letting them know to check their email to confirm their account.

**Comment by nickbrandt** [comment]
@devinreams @sashei 
Will this be needed for Android? I know we initially rolled our own version of this screen for iOS when we didn't have OAuth available, but if we are going out the gates with OAuth in Android, will this still be something we need as a fallback?

**Comment by sashei** [comment]
@nickbrandt probably not; good catch!!

**Comment by linuxwolf** [comment]
Closing this issue as such a screen is unnecessary with OAuth flow.
