### ISSUE TITLE
Handling of accounts with no username

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-android#269]
(on iOS, we have “(no username)” text on entry list, vs on Android, we just don’t show anything). On Entry Detail, on iOS we show blank field with Username label, on Android, we show “Username” as placeholder text. Let's match what we are doing for iOS, designs provided below.

## Visual Design
**InVision**
Entry List: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/346135100_Entry_List_-_No_Username
Entry Detail: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/344036904_Entry_Detail_-_No_Username

**Zeplin**
Entry List: https://zpl.io/andqXJr
Entry Detail: https://zpl.io/2EPN7lD

**Comment by sandysage** [comment]
@changecourse @nickbrandt can you link up the design here so someone can easily implement?
