### ISSUE TITLE
DataStore always defaults to `Unprepared` on app launch

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#275]
The routing is being thrown off because of the `BehaviorRelay` in the DataStore. It defaults to being `Unprepared` when initialized and waits for updated credentials before `Unlock`ing. Instead of assuming that the `DataStore` is always `Unprepared` on startup, we should do the state initialization based on database state or the existence of a set of credentials.

**Comment by hofucy** [comment]
Ha
