### ISSUE TITLE
Auto lock not working

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockbox/lockbox-android#295]
## Steps to reproduce

1. Open Lockbox
2. Tap on "Get Started" and login with any account
3. Open the menu and go to settings
4. In "Configuration" tap on "Auto lock" and set a timer of 1 minute
5. Wait one minute

### Expected behaviour
The app is locked after one minute

### Actual behaviour
The app is not locked after one minute

### Device and build information
- Nexus 5 (Android 6.0.1)
- Huawei Honor 8 (Android 7)
- Nexus 6P (Android 8.1.0)
- Google Pixel (Android 9)
- [Build #1785](https://app.bitrise.io/build/8d9b6261fed6330c)

### Notes
- The same behaviour happens for all of the following scenarios:
    - App in the foreground, screen unlocked, with and without a screen lock set
    - App in the foreground, screen locked, with and without a screen lock set
    - App in the background, screen unlocked, with and without a screen lock set
    - App in the background, screen locked, with and without a screen lock set

**Comment by sandysage** [comment]
@bsurd would you mind testing this again next time you go through the app? I _think_ this is now resolved.

**Comment by bsurd** [comment]
Hello, I've retested this, everything works as expected now, except for the first scenario, that one being when the app is in the foreground and the screen is unlocked, in this case the app does not lock regardless of the fact that you have a screen lock set or not.

@sandysage is this expected? If so, this issue can be closed.

**Comment by nickbrandt** [comment]
@sandysage I believe that is how we ended up developing this feature, to only start the autolock timer once the app is backrounded. Can you confirm @sashei @linuxwolf ?

**Comment by linuxwolf** [comment]
Yes, not locking while in the foreground is expected behavior.

Thanks for retesting @bsurd!
