### ISSUE TITLE
Display list view

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#3]
Upon signing into the Lockbox app, I want to see a list of all my saved entries, by origin name/title. This is so I can easily find an entry, by scrolling, searching, or filtering, to get to that credential quickly.

## Acceptance criteria
* Should be able to view the list of entries by the origin
* Default alphabetical ordering on the origin should make sense (eg facebook comes before twitter)

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979873_Entry_List

**Zeplin**
https://zpl.io/b6MPKgy

**Comment by sashei** [comment]
@nickbrandt @changecourse I can't find a downloadable asset for the disclosure indicator on the list items; can one of y'all point me to it?

thanks

**Comment by nickbrandt** [comment]
@sashei should be able to export it via the Default List item in pattern lib on Zeplin now. Sorry bout that.

https://zpl.io/bPmrX6x
