### ISSUE TITLE
Increase min API version to 24

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#316]
In testing and in discussion at #243 we may not reasonably be able to support Android 6 at launch and need to bump up to Android 7 (API 24) https://github.com/mozilla-lockbox/lockbox-android/issues/243#issuecomment-448013127

**Comment by goodandrewsoft** [comment]
> In testing and in discussion at #243 we may not reasonably be able to support Android 6 at launch and need to bump up to Android 7 (API 24

You really stupid !
![image](https://user-images.githubusercontent.com/2471892/56493789-ee0ce400-64f8-11e9-9ce5-c67f33de162f.png)

What prevents to decrease version?
Laziness or lack of brains?

O my god!
