### ISSUE TITLE
Default Auto Lock timer to "Never" when device security is not set up

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#318]
When a user does not have device security set up on their device, we need to default the Auto Lock timer setting to "Never".

When a user taps on the Auto Lock timer setting, display a dialog to the user informing them in order to update this setting they need to set up device security on their phone.

### Visual Design

**Zeplin**
https://zpl.io/bPv9kgl

**Comment by devinreams** [comment]
iOS: does not let you lock (just throws the alert), does not show autolock timer setting (hidden) if no device security available

**Comment by sashei** [comment]
@nickbrandt @changecourse behavior question: if the user _enables_ device security, should we change the autolocktime setting back to the default (five minutes), or just leave it as `Never` until they set it to something else?

**Comment by sashei** [comment]
@nickbrandt @changecourse similarly, if a user _removes_ device security, should we reset the autolocktime setting to `Never` and disregard the previously-set autolock time value?

**Comment by nickbrandt** [comment]
@sashei I would say: Yes and yes. If the user enables device security, it makes sense to default them to our baseline 5 minutes.

If they remove device security, the auto-lock timer won't be functional, so it also makes sense to reset this to "Never".
