### ISSUE TITLE
Biometric Access Timer

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#32]
## Acceptance criteria
* Should be able to set a timer to lock saved logins
* Should default to being on
* Should be able to set via the settings page (onboarding is different story)
* Should be able to unlock from the same UI as signing in for the first time (until there is a use case for those to be different)
* Should default to 5 minutes until the user sets the timer*
* Should _**not**_ take effect while in the foreground
* Should start when moved to the background
* Should start when quit

### Visual Design

**InVision**
Auto lock dialog: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979888_Settings_-_Auto_Lock

**Zeplin**
Auto lock dialog: https://zpl.io/bLOR9BJ

### Engineering Considerations

* Use absolute UTC date/times for the autolock time
* Calculate and set the autolock time when:
  * the app first starts
  * the app goes into the background (including when the screen goes to sleep)
  * the autolock setting is changed
  * the app transitions to a new activity/fragment (e.g., list view to detail view)
* Assume the app is in the locked state until the autolock time can be compared to the current time

**Comment by sashei** [comment]
@linuxwolf @changecourse @nickbrandt @sandysage did we ever come to a decision about not locking while the app is in the foreground, and instead treating the autolocktime interval as something that "starts" when the app goes into the background?

**Comment by linuxwolf** [comment]
> @linuxwolf @changecourse @nickbrandt @sandysage did we ever come to a decision about not locking while the app is in the foreground, and instead treating the autolocktime interval as something that "starts" when the app goes into the background?

We haven't as far as I know.  I think it's something we should do, but we haven't discussed it.  I'll get an email with pros/cons (as I see them), and we can discuss quickly.

**Comment by sashei** [comment]
Split out issue #219 for the security disclaimer to limit scope on this issue.
