### ISSUE TITLE
App info & promotional asset materials (Play store)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#36]
- [x] Icon
- [x] Feature graphic
- [ ] Video
- [x] Screenshots
- [x] Description
- [ ] Localizations

[image assets.zip](https://github.com/mozilla-lockbox/lockbox-android/files/2527274/image.assets.zip)

**Comment by devinreams** [comment]
Sharing information with the Release Management team here: https://docs.google.com/document/d/1limKjc3Qk2IcqTjoaAPQ7p2yS19O0KNCEAFgqzHKmYU/edit?usp=sharing

**Comment by devinreams** [comment]
A couple of things were requested/highlighted in the release management doc while working to set this up: https://docs.google.com/document/d/1limKjc3Qk2IcqTjoaAPQ7p2yS19O0KNCEAFgqzHKmYU/edit?ts=5bdad2c4

**Comment by devinreams** [comment]
Moving to @changecourse

**Comment by devinreams** [comment]
I'm downloading the assets and will send them to the release team and make sure we have everything we need..

**Comment by devinreams** [comment]
I updated our Play Store listing with the four screenshots and feature graphic provided.

I revised the existing iOS App Store description and re-used it here (eg: replaced "Touch ID and Face ID").

This should all be seen live in the store within hours...
https://play.google.com/store/apps/details?id=mozilla.lockbox

**Comment by devinreams** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/49511/53976540-7b6cb400-40c4-11e9-964d-eab8f2c22f1e.png">

Seen when I was signed in as a tester:
https://play.google.com/store/apps/details?id=mozilla.lockbox&ah=bQcY_hMrUrosQR5VbtzXiwUtCK8
