### ISSUE TITLE
Support text box is overlapping the toggle.

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockbox/lockbox-android#362]
## Steps to reproduce
1. Open Lockbox and log in.
2. From the Menu go into settings.
3. Tap on the Send usage data toggle in the Support section.

### Expected behaviour
Everything looks as expected.

### Actual behaviour
The text description overlaps the toggle hitbox.

### Device and build information
- Sony Xperia Z5 Premium (Android 7.1.1)
- [Build #2068](https://app.bitrise.io/build/5de084abff2a9e31)

### Notes
- Could not reproduce on devices with a higher resolution as the positioning of the text and toggle differ from one device to another.

**Comment by ivanisidrowu** [comment]
Hello, first time here. I would like to work on this issue. :)
