### ISSUE TITLE
The "3 line" menu from FAQ is not dismissed when tapping around it

### ISSUE THREAD

**Issue by abodea** [mozilla-lockbox/lockbox-android#367]
## Steps to reproduce
1. Install lockbox.
2. Login with valid credentials 
3. Reach the FAQ section.
4. Tap on the "3 line" menu also called the hamburger menu.

### Expected behavior
The "3 line" menu is dismissed when tapping around it
### Actual behavior
The "3 line" menu is still displayed when tapping around it and it can be closed only if tapping again on the "3 line" menu.

### Device information
* Firefox Lockbox version: 1.0([build #2068](https://app.bitrise.io/build/5de084abff2a9e31))
* Samsung Galaxy Note 9 (Android 8.1.0)
* Google Pixel 3 XL (Android P/9)
* Samsung Galaxy S7(Android 7.0)
* Samsung Galaxy S8(Android 8.0)

### Notes
Note that the Main Menu(with 3 line menu cotaining the "Acoount, FAQ, Provide Feedback and Settings" can be dismissed by tapping around it.
[Video](https://drive.google.com/file/d/13N828msPZmNxRsUmh8s3sHOU6C7yclke/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2741342/logcat.txt)

**Comment by linuxwolf** [comment]
This issue is with the website's RWD implementation, and not a problem specific to Android.
