### ISSUE TITLE
Hook up FAQ links across the app

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#37]
There are several spots throughout the app that link off to the internal FAQ for support.

Let's use this description to identify 1) the locations in the app that need to link to the FAQ and 2) the exact URL to link to
- [x] **Welcome**
Design: https://zpl.io/VDzrg4v
Link Text: Learn more
Link URL: https://lockbox.firefox.com/faq.html#how-do-i-get-my-saved-logins-into-firefox-lockbox

- [ ] **You're all Set** (onboarding confirmation)
Design: https://zpl.io/V0yxoJQ
Link Text: 256-bit encryption
Link URL: https://lockbox.firefox.com/faq.html#what-security-technologies-does-firefox-lockbox-use 

- [x] **No Entries Found**
Design: https://zpl.io/bAqXRlB
Link Text: Learn more
Link URL: https://lockbox.firefox.com/faq.html#how-do-i-enable-sync-on-firefox

- [x] **No Matching Entries** (when searching)
Design: https://zpl.io/2j4XN1q
Link Text: Learn more
Link URL: https://lockbox.firefox.com/faq.html#how-do-i-create-new-entries

- [x] **Entry Detail**
Design: https://zpl.io/2EAZQyl
Link Text: Learn how to edit this entry
Link URL: https://lockbox.firefox.com/faq.html#how-do-i-edit-existing-entries

- [x] **Send Usage Data**
Design: https://zpl.io/awYA3LK
Link Test: Learn more
Link URL: https://lockbox.firefox.com/privacy.html

blocked by #73

**Comment by changecourse** [comment]
@linuxwolf added!

**Comment by sandysage** [comment]
@changecourse @nickbrandt I'm removing the "needs design" label and marking as P2 to address prior to public launch. Let me know if I made this change in error.

**Comment by sashei** [comment]
@nickbrandt @changecourse just confirming, the title for _all_ of these pages is FAQ, regardless of what portion of the FAQ they link to?

thanks

**Comment by nickbrandt** [comment]
@sashei yep that’s correct!
