### ISSUE TITLE
Make AutofillService domain parsing and matching more robust

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#375]
Related to #372 

Currently, we are naively assuming that android app domains are of the form `x.y.z` where `y` is the domain name to be used for finding potential credentials for autofill.  Additionally, the domain matching uses a string `contains` check, which can lead to false positives and a potential for leaking credentials.

Instead, we should reverse it and use the public suffix list to tease out the top-level "private domain" based on the [PSL](https://publicsuffix.org), and domain name matching should be stricter to exact match or domain "label" descendants.

Some options:
* [Guava](https://github.com/google/guava) has [InternetDomainName](https://github.com/google/guava/wiki/InternetDomainNameExplained) to aid in the last step, though that is quite a lot for a single piece of functionality
* Fennec/FFTV/et al have [support](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/utils/publicsuffix/PublicSuffixPatterns.java) that has been copy-pasta'd around (to be consolidated in [A-C #95](https://github.com/mozilla-mobile/android-components/issues/95) one day)

The preferred approach per a sidechannel conversation with @linuxwolf is that we do the latter; eventually this can be ripped out in favor of `a-c` a la `NetworkStore`, and it will keep our app size down in the long run.

**Comment by linuxwolf** [comment]
When using the results for filling, the checks should be sure to verify the app domain is the same as, or a descendant domain of, what we're testing against.

**Comment by linuxwolf** [comment]
Looking more at the referenced code, it seems like a bad fit for our usage for autofill:
* ~8 months out-of-date from the PSL
* simplified processing the PSL data by moving some of the wildcards and exceptions from the PSL file into code

My opinion is this is fine for simplifying what is displayed to a user, but introduces potential false positives on filling -- meaning credentials could leak.

Investigating just how much "bloat" there is bringing in Guava to start.

**Comment by devinreams** [comment]
@sashei @linuxwolf this is marked as MVP, are you all suggesting we need it before or after initial public launch?

**Comment by jhugman** [comment]
My feelings on this are two fold: 

 * using package ids to string munge an associated domain is going to have spotty success, and add an large extra dependency. Our own apps, `mozilla.lockbox` shows us that relying on the convention of reverse domain names is likely to fail, and for the cases of third party specialist browsers be misleading (e.g. reddit apps)
 * there must be a better way. Can we find the `IntentFilter`s for this app, and look for a `<data android:host="">` entry?

e.g. 

```xml
    <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="http" android:host="www.example.com" />
        <data android:scheme="https" />
    </intent-filter>
```
This is likely yield better results, as apps are likely to provide deep links and verified app links as part of normal development.

I expect we should be able to do this with the `PackageManager`, but it may be a little bit tricky. If that's not possible, then running `adb shell pm` on the device may also be an alternative.

**Comment by linuxwolf** [comment]
If the form is really a WebView/GeckoView, then `getWebDomain()` provides a better result.  Otherwise, from all the information that is available, package name is as good as it gets for mobile-native apps.

It does not appear that `IntentFilter` information from another app is available on-device.

And with all that, checks that make use of the PSL are strongly encouraged to help tighten up domain-matching.

So far, including `InternetDomainName` via Guava increases the APK size by ~700KB.
