### ISSUE TITLE
"Failed to send email" when signing in with Firefox Account

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#378]
Also filed here for FxA team: https://github.com/mozilla/fxa-auth-server/issues/2867
Troubleshooting thread here: https://mozilla.slack.com/archives/C4LNYNJ8G/p1547666141216700

It seems folks are unable to sign in with their Firefox Account on the Android app (but ok on web or iOS app).

![image from ios](https://user-images.githubusercontent.com/49511/51268260-e9c2af00-197c-11e9-8d2e-fa148b36e4f5.jpg)

This appears to be a new bug (within the past 24 hours) and unclear if a bug introduced in our code or upstream (a-c dependency, FxA server or client side).

**Comment by devinreams** [comment]
I actually have old builds (2113, which is not the latest master branch/a-c 0.38.0 build) failing to sign in. And folks on the Play store build are reporting the same (2050) so leads me to believe it's server side and likely not related to android-components...

**Comment by rfk** [comment]
@devinreams this came up in a-s triage, is it now resolved?

**Comment by devinreams** [comment]
Confirmed fixed in production on Lockbox for Android. Thank you for circling back here, @rfk 🙇 

![screen shot 2019-01-23 at 7 23 33 am](https://user-images.githubusercontent.com/49511/51613063-f5aff300-1edf-11e9-9292-45ba1398b062.png)
![screen shot 2019-01-23 at 7 23 55 am](https://user-images.githubusercontent.com/49511/51613064-f6488980-1edf-11e9-86c9-991453d1c262.png)
