### ISSUE TITLE
“Lock now” lock (settings)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#38]
## Acceptance criteria
* Should be able to manually lock saved logins from the settings page

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979874_Entry_List_-_Nav_Drawer

**Zeplin**
https://zpl.io/bLOR9BJ

**Comment by sashei** [comment]
@sandysage @devinreams @linuxwolf would y'all consider this story "done" based on the current behavior? I'm trying to figure out what exactly the behavior should be given the work on clearing the backstack (#143), polishing the nav drawer appearance (#135) and styling the unlock app view (#54)

**Comment by sandysage** [comment]
Confirmed this is in place and the remaining work here is already captured as @sashei noted. Closing.
