### ISSUE TITLE
Force quitting out of Lockbox always brings user back to the Welcome Screen when reopening the app

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-android#387]
Currently, if you force quit out of the Lockbox app after being authenticated, and then re-open Lockbox, the user is brought back to the Welcome screen and has to reauthenticate.

Expected Behavior: User would return to either the Lock Screen or Entry List (depending on user's lock preferences and timing)

**Comment by nickbrandt** [comment]
Just retested this on master (build #2247). Now when force quitting out of Lockbox, instead of being brought back to the Welcome Screen, I am brought to the No Entries Found screen. My entries don't load back, even when pulling to refresh. If I lock Lockbox, and then unlock, the entries return. See below screen capture
![force-quit.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8dfac67964510011279c2f/125516c66e82c728ace21e0d46ee9b882087ceb89ae0ab01e81fe086264c22703d46f96925dce77cbb1a28525b0c1afa465a5f44fefc8c7ff5e06d26984019af80330b2b9b645bf9fa9015ad00bd2a8a4a81beb8894ac9e93f25ef829d02.gif)

**Comment by sashei** [comment]
I'm no longer able to reproduce this after #435

**Comment by nickbrandt** [comment]
No longer being brought back to the Welcome screen ✅ 🎉 
However, I'm seeing the No Entries Found state for a few seconds ❌ , as mentioned (here)[https://github.com/mozilla-lockbox/lockbox-android/issues/386#issuecomment-464192707], then it transitions to the Syncing screen, then displays my entries. ✅

**Comment by devinreams** [comment]
>No longer being brought back to the Welcome screen

Same here 😅 

>I'm seeing the No Entries Found state for a few seconds

Same here.

I filed a separate bug for seeing the "No entries found" flashes at #447. May or may not be related to the full re-sync happening at unlock #360.
