### ISSUE TITLE
Syncing toast notification is missing after pull to refresh added

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-android#388]
Introduced at #48 #232 288817ca96da492e0e18936d526ae1e0e5a96851 but has since disappeared. I will try to bisect and see where/when it stopped appearing.

**Comment by devinreams** [comment]
According to my bisect (20 commits, 5 tries) it looks like pull to refresh #58 #310  ef44428b03c00bfc681f4fa5e66c451566209289 was when the "Syncing.." indicator disappeared.

**Comment by devinreams** [comment]
>Is #360 a duplicate?

@sandysage No, this refers to the little notification at the bottom not showing anymore:

![screen shot 2019-01-23 at 2 31 53 pm](https://user-images.githubusercontent.com/49511/51638469-a4bdf000-1f1b-11e9-9cd1-00c2d79dd14e.png)

The other refers to data not appearing upon sync...

**Comment by nickbrandt** [comment]
@devinreams in addition to missing the bottom snackbar notification, we also had placeholder entries as well (as seen in below image). 

![screen shot 2019-01-23 at 3 33 09 pm](https://user-images.githubusercontent.com/5185090/51641751-3d586e00-1f24-11e9-858e-369a661c5913.png)
