### ISSUE TITLE
'Learn How' link is unclickable

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-lockbox/lockbox-android#405]
### Steps to reproduce
1. Login and click a saved password
2. Click the 'Learn how to edit this entry' text at the bottom of the screen.

## Expected
- Information in some form shows me how to edit the entry.

## Actual
- No difference is seen.

### Device Information
OS: Android 9 (Pixel 2)
App version: 1.0

**Comment by devinreams** [comment]
Related work to happen at #37

**Comment by devinreams** [comment]
This is now clickable 🙃
