### ISSUE TITLE
List is empty even though logged in

### ISSUE THREAD

**Issue by wlach** [mozilla-lockbox/lockbox-android#415]
I'm logged into lockbox with my account, but I'm seeing the "No Entries Found" screen (sounds similar to #360, but in fact nothing ever shows up).

**Comment by linuxwolf** [comment]
If you can recall, were these the steps you took?

1. installed Lockbox
2. followed through "onboarding" (FxA signin)
3. one of:
   - turn off your screen
   - switch to another app (for less than 5 minutes)
   - go to "Recent Apps" and dismiss Lockbox (swipe up/left)
4. relaunch Lockbox
