### ISSUE TITLE
Infrastructure to  search  entries when Autofilling

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-android#421]
### Acceptance Criteria

When launching into the Lockbox search interface, the app switches appropriately from the Locked screen to a placeholder for the item list (or navigates directly to the placeholder when appropriate).

Related to #215

**Comment by jhugman** [comment]
NB According to https://developer.android.com/reference/android/service/autofill/FillResponse.Builder#setFooter(android.widget.RemoteViews) a clickable footer isn't possible.

**Comment by linuxwolf** [comment]
The [documented workaround](https://developer.android.com/reference/android/service/autofill/FillResponse.Builder.html#addDataset(android.service.autofill.Dataset)) is to use a "fake authenticated" dataset.

This means it is possible to have search, but it's in the same system-controlled scroll list as the other real datasets.

**Comment by sashei** [comment]
Outstanding questions from today:
- What should the search dialog look like when there are a lot of entries matching what's typed in the search box (e.g., the user only types `t`)? How should it scroll, and how high should it get?
- What should the behavior be when tapping outside of the search box?

**Comment by linuxwolf** [comment]
[ cc @changecourse @nickbrandt for visibility ]

> * What should the search dialog look like when there are a lot of entries matching what's typed in the search box (e.g., the user only types `t`)? How should it scroll, and how high should it get?

Briefly discussed in standup that it should scroll, but not these particulars.

@changecourse @nickbrandt will have better thoughts, though to start with some strawpeople:

* I think it would be desirable to keep the search bar visible at all times, and scrolling limited to just the login entries
* while it would be nice to keep all of the dialog visible even when the virtual keyboard is open, I don't know how feasible that is.  If not feasible, I would suggest the bottom limit be the same distance as the side margins?

> * What should the behavior be when tapping outside of the search box?

Briefly discussed in standup that it should behave like other dialogs, in that clicking outside should dismiss it and
