### ISSUE TITLE
Use Sync-backed LoginStorage and Remove test data for release/debug builds

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#43]
Actually use the sync keys to get and store data locally and expose in app.

To access my saved logins, I want to safely log into my account and access the common list of entries, confident that my passwords are secure.

## Acceptance criteria
* Should sync with existing store of saved credentials from Firefox in read-only state
* Should sync remote updates (add new, edit, delete) as Sync currently provides for multi-device password sync.
* ~Should track when a username/password are used locally only~ #40 will implement touch

Requires #22

**Comment by devinreams** [comment]
Do we need to keep in-memory storage for UI testing only? (we test against real account/data on iOS, very integration-y and heavy) = Yes, keep it and conditionally consider the environment

**Comment by sashei** [comment]
I added the dependency on #189 because I realized that the interface for the LoginsStorage is also changing as part of that upgrade :p
