### ISSUE TITLE
Link up "256-bit encryption" from the onboarding confirmation screen

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#433]
### Acceptance criteria

From the main onboarding confirmation screen, tapping the `256-bit encryption` text will take the user to an informational page about the encryption used in Lockbox (need link?)

### Designs

[Zeplin](https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen)/5b6915caf290b67d674297dc

Related to #432 

Link: https://lockbox.firefox.com/faq.html#what-security-technologies-does-firefox-lockbox-use

**Comment by devinreams** [comment]
I saw this covered on the second bullet of #37 - want to still plan to cover it off there and close this as a duplicate?

**Comment by sashei** [comment]
whoops!!! thanks @devinreams , let's do it there :)
