### ISSUE TITLE
The hyperlink from FAQ for Contact Us "lockbox-dev@mozilla.com" is not working error[net::ERR_UNKNOWN_URL_SCHEME]

### ISSUE THREAD

**Issue by abodea** [mozilla-lockbox/lockbox-android#444]
## Steps to reproduce
1. Install and launch Lockbox.
2. Tap on **`Learn More`** and scroll until the bottom of the **`FAQ`** page.
3. Under **`Contact Us`** tap on the **`lockbox-dev@mozilla.com`** hyperlink,

### Expected behavior
An email 3rd party app should be opened or a page with fields of `name, device, email, issue` should be displayed when trying to contact the developers / lockbox team.

### Actual behavior
Nothing happens when tapping on the `lockbox-dev@mozilla.com` hyperlink and the following error is displayed **`[net::ERR_UNKNOWN_URL_SCHEME]`**

### Device information
* Firefox Lockbox version: 1.0 [build #2561](https://app.bitrise.io/build/8e95ac67b65f0d76)
* Samsung Galaxy Note 9(Android 8.1.0)
* Google Pixel 3 XL (Android P/9)

### Notes
Note that no matter from where you open `FAQ` welcome screen or three line menu after you logged in, the hyperlink is not working.
[Logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2869757/Logcat.txt)
![img_20190215_171600](https://user-images.githubusercontent.com/42831109/52865676-d191ab80-3145-11e9-8293-bcb3c56bd75a.jpg)

**Comment by sandysage** [comment]
We're removing the "contact us" link from the FAQ. Closing this out from the Android repository.
