### ISSUE TITLE
Create an Android test plan

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#45]
Test Rail:
https://testrail.stage.mozaws.net/index.php?/suites/view/3060

**Comment by iamVP7** [comment]
Would like to contribute as manual tester. Experienced in Java coding in server side.

**Comment by devinreams** [comment]
Thank you @iamVP7! We will get our test plan documented for routine runs and once we have code _and_ functional tests in place and feel like its worth your time we'll get you added as an early tester.  😁 

Thanks again for the offer.

**Comment by devinreams** [comment]
Test plan drafted by re-purposing iOS testing, PI / QA team is still chipping away at it but wanted to share the (internal) link here for now:

https://testrail.stage.mozaws.net/index.php?/suites/view/3060
