### ISSUE TITLE
Implement an explicit default state in nav controller (show a blank or simple layout  vs "no entries list")

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#452]
Currently the splash screen that displays Lokie is a variant of the entry list and not an explicit view. We're finding a few potentially related issues around "no entries found" displaying at seemingly odd times:

* #448
* #447
* #440 (maybe)
* #415 (maybe)

**Comment by devinreams** [comment]
For what its worth: the autofill implementation just throws a blank/empty fragment.

Either way "no entries list" is not the right default.
