### ISSUE TITLE
The "FAQ" page can be opened from the "You're all set!" screen after a login

### ISSUE THREAD

**Issue by abodea** [mozilla-lockbox/lockbox-android#455]
## Steps to reproduce
1. Install and launch Lockbox.
2. Tap on "Get Started" and the enter your email.
3. Login with valid credentials.
4. Wait until the "You're all set!" page is displayed.
5. Tap anywhere around the "Sync between devices with secure 256-bit encryption" icon/text.

### Expected behavior
Tapping anywhere on the "You're all set!" will not open a link/hyperlink that is not present there.
### Actual behavior
When tapping around "Sync between devices with secure 256-bit encryption" icon/text the "FAQ" page is opened but there is no link/text there regarding "FAQ" page.

### Device information
* Firefox Lockbox version: 1.0 [build #2626](https://app.bitrise.io/build/bf9242396ba0f030)
* Samsung Galaxy Note 9(Android 8.1.0)
* Google Pixel 3 XL (Android P/9)

### Notes
There in the "You're all set!" page the "FAQ" link/text is not present and the links cannot be seen.
[Video](https://drive.google.com/file/d/13uMYYenEFsB9oDw81hkKkd3K5YRfyV3I/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2885492/logcat.txt)

**Comment by diegolucasb** [comment]
@abodea, I'd like to work on this issue. Can you assign it to me?
