### ISSUE TITLE
Feedback can be sent even if no options/stars are selected

### ISSUE THREAD

**Issue by abodea** [mozilla-lockbox/lockbox-android#461]
## Steps to reproduce
1. Install and launch Lockbox.
2. Tap on **`Get Started`** and the enter your email.
3. Login with valid credentials.
4. Tap on 3 line(hamburger menu).
5. Tap on the **`Provide Feedback`**
6. Tap on **`Submit`** button.

### Expected behavior
When no options are selected in the **`Feedback`** menu, an error should be displayed, telling the user to select between 1-4 stars and the additional options from feedback.
### Actual behavior
When tapping on the **`Submit`** button, the feedback is submitted eve when no stars / options are selected.

### Device information
* Firefox Lockbox version: 1.0 [build #2681](https://app.bitrise.io/build/bf9242396ba0f030)
* Samsung Galaxy Note 9(Android 8.1.0)
* Google Pixel 3 XL (Android P/9)

### Notes
At least few options to select when giving feedback should be mandatory.
[Video](https://drive.google.com/file/d/14z5zP-5jp_ULgYhhnP2QJeEBQTbnPL3C/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2889843/logcat.txt)

**Comment by sandysage** [comment]
This is intentional behavior. Closing
