### ISSUE TITLE
DataStore List not quite ready when `Locked` / `Unlocked`

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-android#464]
When the DataStore's state transitions to `Locked` or `Unlocked`, the "published" list of credentials is reconciled (cleared or updated), and other components within Lockbox use this transition as a cue.

However, updating the published list is an asynchronous operation which means it is not complete before other subscribers to the `DataStore.state` observable are notified; this can lead to some odd behaviors:

* Unlocking during autofill results in no fillable credentials
* "No entries" might be shown temporarily

Related to #447

**Comment by devinreams** [comment]
Effect is the user will get kicked back to "search" so if we can fall back and rely on that, this is probably safe to downgrade.
