### ISSUE TITLE
Backgrounding Autofill for some period > autolock time will launch the fingerprint dialog again

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-android#489]
Steps to reproduce:
- Launch into the Search view in autofill (either unlocking or from Search Your Entries row)
- Use the home button or simply let the device go to sleep for > 5minutes (or whatever the autolock time is)

**expected:** the search dialog goes away, only the fingerprint dialog remains
**actual:** a second fingerprint dialog is launched over the search dialog. unlocking brings you to a second search dialog.

**Comment by devinreams** [comment]
Perhaps low likelihood since the user is actually going to go through all the steps at once, but it's possible (low freq, mid impact) with easy workaround.
