### ISSUE TITLE
Auto lock menu appears when foregrounding app

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockbox/lockbox-android#507]
<img width="350" alt="Screenshot (Mar 18, 2019 12_58_18 PM)" src="https://user-images.githubusercontent.com/43795363/54560207-09775300-497f-11e9-9595-0d18cf3cf749.png"> 

Steps to reproduce:

1. Open the app
2. Sign in with test account
3. No fingerprint
4. Set as autofill provider
5. Go to settings
6. Set Auto lock time to 1 minute
7. Go to item list 
8. Background the app
9. Foreground the app — see that the auto lock menu is above the item list

**Comment by sandysage** [comment]
This should be addressed with #499. Let's confirm and close.

**Comment by eliserichards** [comment]
Confirmed that this is no longer reproducible. Closing!
