### ISSUE TITLE
Duplicate credentials displayed in entries screen

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockbox/lockbox-android#511]
### Steps to reproduce
1. In FF go to settings and login on several devices.
2. When prompted to remember the username and password tap on Remember.
3. Go into lockbox and login with the same account.
4. Wait for entries to be displayed.

### Expected behaviour
Only one unique entry is displayed.

### Actual behaviour
Multiple entries of the same type are displayed.
![screen](https://user-images.githubusercontent.com/17178945/54612341-74995600-4a61-11e9-9699-2292bf6dac56.png)

### Device and build information
- Nokia 6 (Android 7.1.1)
- Nexus 6P (Android 8.1)
- OnePlus 5T (Android 9)
- [Build #3073](https://app.bitrise.io/build/bfc81baa006472b2)

### Notes
- If logging on desktop on the same account and remembering the username and password another entry is not created.

**Comment by sashei** [comment]
This isn't a problem with the android app; it represents a background issue in which Sync allows multiple entries for the same account.

**Comment by eggsgent** [comment]
> 
> 
> This isn't a problem with the android app; it represents a background issue in which Sync allows multiple entries for the same account.

Hi, do you by any chance have a bug number for the Sync dupe issue? Didn't find anything related in bugzilla.
