### ISSUE TITLE
Autofill option is missing from settings on Android 7 devices

### ISSUE THREAD

**Issue by abodea** [mozilla-lockbox/lockbox-android#512]
## Steps to reproduce
1. Install lockbox.
2. Tap on "Get Started" and the enter your email.
3. Add all the required information and log in.
4. Tap on 3 line menu and open Settings.

### Expected behavior
The autofill option is missing from the settings menu.

### Actual behavior
The autofill option is displayed in settings menu and works accordingly.

### Device information
* Firefox Lockbox version: 1.0([build #3073](https://app.bitrise.io/build/bfc81baa006472b2))
* Sony Xperia Z5(Android 7.0)
* Samsung Galaxy S7 (Android 7.0)
* Nokia 6 (Android 7)

### Notes
Note that after sign in there is no prompt regarding the autofill option.
[Video](https://drive.google.com/file/d/1WmnL1KgnaUmgTXnbXzngDvk217TJeI80/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2983763/logcat.txt)

**Comment by sandysage** [comment]
This is by design. Autofill is not available on 7.0 and below.
