### ISSUE TITLE
"Make sure your finger covers the entire sensor" text error is not correctly aligned

### ISSUE THREAD

**Issue by abodea** [mozilla-lockbox/lockbox-android#514]
## Steps to reproduce
1. Install lockbox.
2. Tap on "Get Started" and the enter your email and log in.
3. Add all the required information and log in.
4. Tap on 3 line menu and open Settings.
5. Tap on the Configuration option and activate fingerprint.
6. Tap back and lock the Lockbox.
7. Tap on unlock and drag your finger from right to left until `"Make sure your finger covers the entire sensor"` error is displayed.

### Expected behavior
The text error is aligned correctly.
### Actual behavior
"Make sure your finger covers the entire sensor" text error is not aligned correctly.
### Device information
* Firefox Lockbox version: 1.0([build #3073](https://app.bitrise.io/build/bfc81baa006472b2))
* Samsung Galaxy Note 9(Android 8.1.0)

### Notes
I was not able to reproduce this issue on Google Pixel 3 as the fingerprint path/mechanic is different from Samsung Galaxy Note 9 and once I put a little part of my finger on the scanner it recognize it.
![IMG_20190319_161612](https://user-images.githubusercontent.com/42831109/54617726-82070e00-4a6a-11e9-99a7-c4e6be84aa2f.jpg)

**Comment by pavelbay** [comment]
Hi. Would like to contribute, but not be able to perform a git push. Do I need extra permissions for this? Could not find any related infos. Thanks in advance.

**Comment by deandreamatias** [comment]
@pavelbay you make a pull request in master branch? Please, describe better your steps to helping you. Thanks.

**Comment by pavelbay** [comment]
@deandreamatias thanks for your answer. I created a local branch from master, fixed the issue there and tried to push firstly from android studio and then from git bash with `git push origin -u <my_branch_name`. In case of using https received 403, then I tried the same using ssh and got permissions denied.

**Comment by linuxwolf** [comment]
@pavelbay Thanks for your interest!

In order to create a pull request, you can:

1. fork this repository (and clone your fork locally)
2. create a branch and make changes
3. push your branch (with the cahnges) to your fork of the repo
4. create a pull request from your branch/fork to this repo's `main`
