### ISSUE TITLE
Add l10n toml

### ISSUE THREAD

**Issue by Delphine** [mozilla-lockbox/lockbox-android#519]
This is only a configuration change, to be used by the upcoming l10n ecosystem. Thus not tests or changelogs or QA tags on this one.
CC @Pike 

Related to #46

**Comment by Pike** [comment]
@devinreams, can you assign this to me? Thanks.

**Comment by sandysage** [comment]
This ticket is no longer actionable for the Lockbox team. I'm going to go ahead and close this ticket knowing we'll continue to work together in other tickets.
