### ISSUE TITLE
Privacy policy misformatted

### ISSUE THREAD

**Issue by callahad** [mozilla-lockbox/lockbox-android#533]
This is a tiny nit-pick, but the privacy policy (accessed via the Learn More link under the telemetry in Settings) appears to be misformatted.

1. "Interaction data." should start a new bullet point, but is merged with the prior entry.
2. "Credential data:" ends with a colon; everything else with a period.

The first one genuinely forced me to stop and re-read that paragraph a few times before I realized it should be the start of a new list item.

**Comment by devinreams** [comment]
Nice catches, thanks @callahad
