### ISSUE TITLE
Splash Screen/Get Started Lockie Mismatch

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-android#541]
Splash screen appears to be condensed/vertically smashed and isn't seamless with the get started Lockie image. It pops during the transition between screens. 

Device tested: Pixel 2
Version: 1.0 public

**Comment by deandreamatias** [comment]
Test and gave me the same problem. It happened to me only when I unlock with a numerical combination. I'm already trying to solve it.

**Comment by deandreamatias** [comment]
I got to find out why this issue occurs. It happened to me only when I unlock with a numerical combination because the keyboard does not close in time for the button and the image to 'go down' to its original position.
All this happens very fast, that's why this error occurs.
