### ISSUE TITLE
Enable autofill (settings)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#56]
## Acceptance criteria
* Should be able to enable autofill (OS) from Lockbox settings
* Should actually reflect the enabled/disabled state of Lockbox as an enabled/disabled provider
  - how do we check for current state of autofill provider? (Can we confidently say “Yes” Lockbox is enabled). other apps seeming can/do...

Note: see commented/disabled code and tests at #289 

### Visual Design

**InVision**
Settings: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979885_Settings
Opens Device Autofill Settings: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/314387970_AutoFill_-_Settings
Confirmation Dialog: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/314387969_AutoFill_-_Settings_-_Confirm

**Zeplin**
Settings: https://zpl.io/awYA3LK
Opens Device Autofill Settings: https://zpl.io/VYRpzym
Confirmation Dialog: https://zpl.io/agNkEXN

Requires #214

**Comment by sashei** [comment]
Behavior question for @nickbrandt @changecourse @sandysage :

What should happen when toggling the autofill setting from _on_ to _off_? The API usage guidelines suggest that we shouldn't launch the autofill system setting when we are already the autofill provider (but tbf don't enforce that requirement). I'd assume the intent is that we would launch the system settings in that case though.

**Comment by nickbrandt** [comment]
@sashei I'm actually inclined to say we don't need to launch the settings in this case. The reason it makes sense when enabling the feature is it requires a confirmation dialog for that case. I think simply removing Lockbox as the provider when tapping the toggle in our settings and remaining in our app would be preferred. 1pass also handles it this way, though Dashlane and Lastpass do take the user back to settings. Open to your thoughts as well though @changecourse @sandysage

**Comment by sashei** [comment]
@nickbrandt sounds good! One more question, should a user reset (resets all of our other settings) also remove lockbox as the credential provider?

**Comment by linuxwolf** [comment]
While subject to @sandysage chiming in ...

I believe the basic premise of reset is that (as much as possible) it be a proxy for uninstalling/reinstalling.  I'm assuming uninstalling an app would reset the autofill state, so therefore we should do the same on reset if possible.
