### ISSUE TITLE
Shadow is missing from App Bar

### ISSUE THREAD

**Issue by pwd-github** [mozilla-lockbox/lockbox-android#565]
The shadow (elevation) is missing from the app bar, making the entire app look flat. It distracts from the polish of the app.

I would link to the page on the material design website, but that website is terrible now and it's impossible to use it as a reference.

**Comment by deandreamatias** [comment]
Hi @pwd-github. Do you say the shadow like this image?
![image](https://user-images.githubusercontent.com/21011641/55282600-54ae4000-5347-11e9-9fc2-2ff8dedd6a53.png)

**Comment by pwd-github** [comment]
Yep, that's exactly the shadow I'm referring to.

**Comment by deandreamatias** [comment]
I try to fix this tomorrow. Thanks.

**Comment by pwd-github** [comment]
You're awesome. Thank you @deandreamatias
