### ISSUE TITLE
No Matching Entry - Search/Filter (list view)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#57]
## Acceptance criteria
* When searching for an entry and there are no matching results, should inform the user nothing is found and how to add logins to Firefox Lockbox

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979880_Entry_List_-_Search_-_No_Matches

**Zeplin**
https://zpl.io/2j4XN1q

**Comment by devinreams** [comment]
Confirmed this was implemented at #109 

Expected:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/49511/46635772-c208b300-cb12-11e8-9813-4f3273f35545.png">

Actual:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/49511/46635764-b917e180-cb12-11e8-8a02-4f0c2ad32623.png">


As seen above, some final layout/spacing changes are needed but closing this as complete
