### ISSUE TITLE
String updates for first L10n export (2nd review)

### ISSUE THREAD

**Issue by Delphine** [mozilla-lockbox/lockbox-android#579]
I've done another pass at the [current strings.xml file](https://github.com/mozilla-lockbox/lockbox-android/blob/master/app/src/main/res/values/strings.xml), and have found a few remaining "issues" that need to be fixed (most are simply nits).

- [x] The app name (Firefox Lockbox) appears throughout the file. This means that it *can* be translated - is that ok with you? Also, are we sure the app name will not change over time? 
In other mobile products we tend to use a placeholder, just in case: '%1$S' - and we always have a note in the comments saying the placeholder will be replaced by the app name
Up to you! (note that if you want to keep this as is, then you'll have to make sure to call out in all the comments that the app name shouldn't be translated - which is not the case right now (just a few missing))
- [x] Mentions of Firefox Account and Firefox: I think these also appear this way in Firefox files (@Pike can confirm just in case), so it should be ok to leave as is? (as long as it's mentioned not to translate them in the comments). Not entirely sure, I'll go with Pike's recommendation for these
- [x] Apostrophes: we use curly quotes and apostrophes in strings (not needed in localization notes). I see some have been updated, but not all (also no need to use a slash)
- [x] [L27](https://github.com/mozilla-lockbox/lockbox-android/blob/5aa1c97d7aa3c80d3a4dbb6f45eb5e8ac8b4c9c9/app/src/main/res/values/strings.xml#L62): This should be moved to non_localizable_strings.xml
- [x] [L228](https://github.com/mozilla-lockbox/lockbox-android/blob/5aa1c97d7aa3c80d3a4dbb6f45eb5e8ac8b4c9c9/app/src/main/res/values/strings.xml#L228): here it just says "Lockbox", probably better to remain consistent with the rest ("Firefox Lockbox"), unless there's a good reason not to
- [x] [L238](https://github.com/mozilla-lockbox/lockbox-android/blob/master/app/src/main/res/values/strings.xml#L238): please explain in comments what ' %s' refers to
- [x] [L195](https://github.com/mozilla-lockbox/lockbox-android/blob/5aa1c97d7aa3c80d3a4dbb6f45eb5e8ac8b4c9c9/app/src/main/res/values/strings.xml#L195) and [L197](https://github.com/mozilla-lockbox/lockbox-android/blob/5aa1c97d7aa3c80d3a4dbb6f45eb5e8ac8b4c9c9/app/src/main/res/values/strings.xml#L197): Formatted as comments instead of strings

**Comment by Pike** [comment]
Leaving Firefox branding in is OK, with a comment.
Note, we do localize "Firefox Account", https://transvision.mozfr.org/string/?entity=browser/browser/branding/sync-brand.ftl:-fxaccount-brand-name&repo=gecko_strings. So yes, leave that in. If you want to highlight that, note that this should be translated consistently with other Firefox products.

**Comment by Delphine** [comment]
As per discussion on Slack, I confirm all occurrences of this apps name should appear as a placeholder

**Comment by devinreams** [comment]
Thanks, @Delphine @Pike. Here's a pull request with all the changes and explanations to help remedy/close all these findings:
https://github.com/mozilla-lockbox/lockbox-android/pull/617
