### ISSUE TITLE
Long email is cut a little bit at the end in the Sign in screen

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-android#581]
Not sure if it is actually a Lockbox issue...not very critical either but it does not look totally fine so I thought I had to open an issue to let you know. Sorry if it is already addressed in another issue, could not find a similar one...

- Log in with a long email

Please see screenshot:
![IMG_2376](https://user-images.githubusercontent.com/1897507/55719762-52ab4780-59ff-11e9-8ad1-42d4ecfa0527.JPG)

**Comment by devinreams** [comment]
Ah yes, there is a proposal to redo the screens to handle long addresses better on the FxA side here:
https://github.com/mozilla/fxa/issues/605
