### ISSUE TITLE
Improper redirect after setting Lockbox as your autofill service, stuck on "You're all set" during onboarding

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockbox/lockbox-android#582]
## Steps to reproduce
1. Open Lockbox and tap on Get Started.
2. Enter any account and password.
3. In the next screen select go to settings in order to set Lockbox for password autofill.

### Expected behavior
A "You're all set!" screen is present with a finish button at the bottom. 

### Actual behavior
The screen has no finish button. There is no option to get out of the screen.

### Device information
* Firefox Lockbox version: 1.0 [build #3334] from Play Store
* Nexus 6P (Android 8.1)

### Notes
* Could be related to #580 .
* There is a workaround of going back and selecting the skip option or closing and reopening the app.
* [Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/3053994/log.txt)
* ![picture](https://user-images.githubusercontent.com/17178945/55720011-614a2c80-5a08-11e9-99e1-07a18a7da8e4.jpg)

**Comment by devinreams** [comment]
I encountered this during testing too and it prevents me from opening up Lockbox, so a very poor first run user experience and worth prioritizing as its a big regression.

**Comment by devinreams** [comment]
@eliserichards @sashei Another interesting side effect, if it's helpful to track it down:

- open settings screen
- disable Autofill toggle
- enable Autofill toggle
- go to system settings and set "Lockbox"
- settings routes back to Lockbox settings screen

Expected: settings screen looks normal and grey

Actual: settings background color is dark blue 🤷‍♂️ 

![IMG_2528](https://user-images.githubusercontent.com/49511/56432719-b0efea00-628b-11e9-9f4c-5b1f4b5a81c0.jpg)

**Comment by abodea** [comment]
Hello, note that I was able to reproduce this issue on a **`Google Pixel 3 XL (Android P)`**.
I also tried to reproduce it on the following devices: **`Google Pixel XL(Android Q), Samsung Galaxy Note 9 (Android 8.1.0), Samsung Galaxy S8 +(Android 8)`** but I couldn't reproduce the issue.
Here is the [logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/3103791/logcat.txt) for the Google Pixel 3 XL (Android P) device.
![20190422_175407](https://user-images.githubusercontent.com/42831109/56507265-6be8e380-6529-11e9-8a80-1f5c8336afd1.jpg)

**Comment by eliserichards** [comment]
@abodea I'm still having trouble reproducing this bug. Can you try uninstalling your instance of Lockbox and reinstalling it again (on your pixel 3 xl with P) and see if you're still getting the bug?

**Comment by devinreams** [comment]
@eliserichards I just upgraded to 1.0.3 Alpha in Play Store on a Pixel 2, Android 8 and encountered this "You're all set!" still. ❌ 

I then uninstalled and re-installed it and encountered it still. ❌ 

I think uninstalled and re-started the phone and re-installed and encountered it still. ❌ 

I also still get the blue settings screen if I trigger the "Autofill" setting from there and jump back from settings into the app.

**Comment by eliserichards** [comment]
Pixel 2, Android 9.0:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/43795363/56928699-7efd3580-6a8c-11e9-8725-220729823346.png">

Pixel 2, Android 8.1:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/43795363/56928914-13679800-6a8d-11e9-9abe-d4c5b10785f7.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/43795363/56928926-211d1d80-6a8d-11e9-8110-3c1f4a672015.png">
