### ISSUE TITLE
Settings view

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#6]
When I want to customize my in app experience, I need to easily find those settings clear instructions for how to curate my in-app settings as well as delete my account.

## Acceptance criteria
- [x] Should be able to close out of the settings view to get back to the entry list
- [x] Should be easily accessible from Navigation Drawer
- [x] Should include the setting option list of
   - [x] Turn On/Off Fingerprint
   - [x] Change Auto Lock timer
   - [x] Turn On/Off AutoFill (this will actually just display whether the setting is turned on/off in settings. tapping this toggle would route the user to the setting on their device)
   - [x] Turn On/Off Sending Usage Data
   - [x] Display the App Version

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979885_Settings

**Zeplin**
https://zpl.io/awYA3LK

Remaining engineering todos:
- [x] toggle cell with link
- [x] app version
- [x] force cast in  `SettingFragment`
- [x] SettingPresenter test
- [x] settingListAdapter test
- [x] sectionlistadapter test
- [x] check bitrise

**Comment by sashei** [comment]
@nickbrandt @changecourse what should the behavior of the app version be on very small screens? @eliserichards and I are worried about the settings view being able to scroll _under_ it in some cases. Could it be part of the settings list or ??

**Comment by changecourse** [comment]
Ah, makes sense... ok, we're updating the positioning of the App Version to be anchored to the base of the settings list view, rather than the base of the device. Does that work?

**Comment by sashei** [comment]
@changecourse sounds good!! that looks much easier implementation-wise.

thanks!

**Comment by eliserichards** [comment]
Adding my pseudo-UML diagrams of the two proposed implementations (hard-coded sectioned view and PreferenceFragmentCompat). (These were just made for my own reference)
![settings_view_original_impl](https://user-images.githubusercontent.com/43795363/47383293-42a1e480-d6b9-11e8-93cb-83e46c0e473c.jpg)
![preferencefragcompat_proposed](https://user-images.githubusercontent.com/43795363/47383298-46356b80-d6b9-11e8-901e-d79d455d6f56.jpg)

**Comment by devinreams** [comment]
Thanks for adding those! They’re a great practice, help improve clarity and understanding, and can be really helpful to come back to in a few weeks/months if we need to retrace our steps and thinking.
