### ISSUE TITLE
Delete entries

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#601]
When I notice I have duplicate or inaccurate entries, I want the ability to delete the credential entirely from my database.

## Requirements
* Should provide the ability to delete from the entry detail view #626 
* Should provide the ability to delete from the entry edit view #628 #630 
* Should have a disclaimer that I have to confirm when deleting a record #627 
* Should have ability to cancel the delete request #627 
* Should not have the ability to undo (can consider as a future request)
* Should display toast to confirm deletion on returning to entry list #629

NOTE: public release should include both edit and delete because flows are intrinsically tied

Future requirement (not in scope): ability to delete entries from the list view.

## Epic Acceptance criteria

All requirements are addressed by engineering stories.

**Comment by devinreams** [comment]
Investigation/break out issue is satisfied with the follow up stories created and linked above.

Thanks @sashei 🙌
