### ISSUE TITLE
Enable UI Tests on Bitrise

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockbox/lockbox-android#619]
Work is on going to have the tests enabled again for commits on master. 

There is a new workflow created where tests start running: `testing-enable-ui-tests`

But still some work pending since tests start but fail and not all of them are executed. [Logs here](https://storage.googleapis.com/bitrise-addon-ftl-prod-bucket/android-tests/37db027de0659b7b/results/Pixel2-27-en-portrait/logcat?Expires=1555945363&GoogleAccessId=bitrise-addon-ftl-prod-serv-ac%40bitrise-addon-ftl-prod.iam.gserviceaccount.com&Signature=ET1c74TiY6eq3byNnECxKgXWo8qQncOR14kk1XXEvZ85IQ4DUspD5IRBXa8ooO1gixXlAKZKoSy3aoV5kUT0Bx0GXQvYg3gKZ97Va7eutptZP6mnxdG5ddOLeujC8F8%2BkDnrHiOkyLAMmkQiPknzAf4YDMIdrTobLOBrgrzTW3oMuIU%2FssmVXbPiEeOCPx3NRv7f0anaoivt%2FRi3WNmZzOX2XQppxWi8ZTqzM9KZEdBbf3F%2B2MwFOaGLSCI0clfQRzX6332KLeUk5ND%2Bhx7Oy9T30YtFF6mtVXipoVy8q0pozVmfFsBu6fiHbwmbp9oe3qxquKzz53cuwcbKnhQyHw%3D%3D)

All existing (and enabled) tests are running fine locally, once this is fixed and tests run on CI we will focus on creating more tests to increase the coverage.

**Comment by devinreams** [comment]
Closed at #620
