### ISSUE TITLE
Implement app icon

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-android#63]
Provide necessary assets for Android app icons.

### Image Assets
Using the images below, you can generate all of the assets needed for launcher icons within Android Studio. (Right click 'res' folder > New > Image Asset)
[app-icon.zip](https://github.com/mozilla-lockbox/lockbox-android/files/2255007/app-icon.zip)

![android-studio](https://user-images.githubusercontent.com/5185090/43608486-72d4aae8-965e-11e8-971a-f808755d84ae.png)

**Comment by devinreams** [comment]
@nickbrandt now that we have a placeholder Android project (code in this repo) do you want to check in the assets yourself? or have engineering do it and double check and then back to you to review?
