### ISSUE TITLE
Lock Now dialog for users without a device PIN set up

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-android#64]
When the user does not have biometrics or a device PIN set up, upon tapping the "Lock Now" option from the navigation drawer, a dialog should inform the user that they must set up a device PIN in order to lock the app.

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/311904836_Entry_List_-_Nav_Drawer_-_Lock_-_No_PIN

**Zeplin**
https://zpl.io/bWY9MwK

**Comment by sashei** [comment]
@nickbrandt @changecourse it's going to be non-trivial to keep the app drawer open when displaying the dialog for this case; are we OK with closing it when displaying the dialog to limit the scope of this story?

**Comment by nickbrandt** [comment]
@sashei Yep I think that would be fine
