### ISSUE TITLE
Implement Biometric (fingerprint) unlock fragment/activity

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-android#68]
Implement the Activity or FragmentActivity for [Unlock Firefox Lockbox](https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/310606417_Lock_Screen_-_Fingerprint) design.

* Uses FingerprintManager API to engage hardware when initialized
* Cancel hardware when user clicks "Cancel"
* Dismiss (Fragment)Activity when hardware successfully unlocks via fingerprint
* Fallback to device PIN when the user requests it

Related #28 
Required by #31
Required by #32
Required by #69
Required by #70
Required by #118
Required by #144

**Comment by ioana-farcas** [comment]
@nickbrandt , @changecourse 
Which should be the behaviour of the app when the fingerprint authentication fails?
If the fingerprint authentication fails for 5 times in a row, the fingerprint sensor will be unresponsive for 30 seconds, and the API sets a message for the error: "Too many attempts. Try again later" (the error message can be changed in the dialog).

Also in other apps (for unlocking the screen is the same), when the fingerprint authentication fails for 5 times in a row, the behaviour is to fallback to other type of authentication. If for this other type, in our case PIN, the authentication will fail again for 5 times in a row, the user will not be able to unlock app for 30 seconds. After those 30 seconds pass, the user can use fingerprint or pin to authenticate.

I added a screenshot with the dialog, please advise how do you think the designs and the UX should be/look like for this scenario and please let me know what do you thing about falling back to PIN, taking into account that the sensor will be unresponsive for 30 seconds when fingerprint auth fails.

![fingerprint_fail](https://user-images.githubusercontent.com/16756095/47139419-79948680-d2c4-11e8-8bcb-c1f0e7f642df.jpg)

**Comment by changecourse** [comment]
My hope for how we handle this, based on a conversation with @linuxwolf would be as follows:

1. Present fingerprint auth for the first 5 attempts (solely)
2. Then direct user to Device PIN input automatically
3. After all attempts for both fingerprint auth and device pin have failed, present lockout messaging

How automated we are able to be (as referenced in no. 2 may need to still be up for discussion.

**Comment by changecourse** [comment]
@nickbrandt there was a request in stand-up to confirm the following states (or approve the default styling by Android) 

1. Fingerprint unlock failed (too many attempts)
2. PIN unlock failed (too many attempts)
3. Lockout state

**Comment by nickbrandt** [comment]
Yes, and after talking with @ioana-farcas I think it does make sense to display a different message briefly to the user of "Too many attempts", then route the user to the device auth screen. I agree with using the default styling by Android for those instances. My assumption if the user fails device auth, is that we display a message of "Too many attempts. Try again later." and route the user back to where they were (either Lock Screen or wherever they were authenticating to use autofill)
