### ISSUE TITLE
Include Adjust integration

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#74]
- [x] Integrate the Adjust SDK: should be in the APK module's build.gradle, see instructions [here](https://github.com/adjust/android_sdk#add-the-sdk-to-your-project)
- [x] Set up the Lockbox Android token: 383z4i46o48w
  - [x] Provide marketing with the app ID (mozilla.lockbox)

**Comment by devinreams** [comment]
@ssage our App ID is: mozilla.lockbox (can you please get us the token)

**Comment by sandysage** [comment]
@devinreams we should be able to use this token: 383z4i46o48w
